language: node_js
node_js:
- "node"
script:
- "npm run build"
settings: 
    build_pushes: true
addons:
  code_climate:
    repo_token: 5d911e7c70b84a87eac0b3565e017bf29e352ed619808cc2a16ba2350a3434b2
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
